// THIS FILE ONLY FOR MOCKING USERCODE BUILD
// BECAUSE TO START BUILD CODE GITCALL REQUIRES
// THE PRESENCE OF USERCODE FILE INTO THE REPO
// THE FUNCTIONAL CODE WILL BE COPIED TO THIS FILE AFTER THE BUILD
// WITH THE BUILD COMMAND THAT PASSED INTO THE GITCALL CLIENT
// SEE USERCODE_BUILD_SCRIPT variable into the build/.gitlab-ci.yml FOR MORE DETAILS

module.exports = (data) => {
    return data;
};
